# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 03:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('turno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('hora_inicio', models.DateTimeField(auto_now=True)),
                ('hora_fin', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva')], default='inactiva', max_length=10)),
                ('asesor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asesor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='turno',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_turno', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='turno',
            name='recepcionista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recepcionista', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cita',
            name='turno',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='turno.Turno'),
        ),
        migrations.AddField(
            model_name='cita',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_cita', to=settings.AUTH_USER_MODEL),
        ),
    ]
