# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 18:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turno', '0003_auto_20170214_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='asesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asesor_citas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cita',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_citas', to=settings.AUTH_USER_MODEL),
        ),
    ]
