# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turno', '0004_auto_20170214_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='turno',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='turno.Turno'),
        ),
    ]
