# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 22:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('turno', '0005_auto_20170214_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='asesor',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='turno',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='usuario',
        ),
        migrations.RenameField(
            model_name='turno',
            old_name='ticket',
            new_name='turno',
        ),
        migrations.AddField(
            model_name='turno',
            name='asesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asesor_citas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva')], default='inactiva', max_length=10),
        ),
        migrations.AddField(
            model_name='turno',
            name='fecha_fin',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='fecha_ingreso',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='fecha_inicio',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Cita',
        ),
    ]
