# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turno', '0007_auto_20170214_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='asesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asesor_turnos', to='account.Usuario', verbose_name='Asesor que atiende al Usuario en este turno'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='recepcionista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recepcion_turnos', to='account.Usuario', verbose_name='Persona que asigno la cita'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_turnos', to='account.Usuario', verbose_name='Usuario al que se le asigna el turno'),
        ),
    ]
