# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turno', '0009_auto_20170221_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='turno',
            field=models.CharField(default=5, max_length=5, null=True),
        ),
    ]
