# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='rol',
            field=models.CharField(choices=[('recepcion', 'Recepcion'), ('atencion', 'Atencion'), ('admin', 'Administrativo'), ('usuario', 'Usuario')], default='atencion', max_length=20),
        ),
    ]
